"$schema" = "./config_schema.json"

[host]
gitlab = "git@gitlab.com:${repo/name}.git"

[host.github]
host = "ssh://gh/${repo/name}.git"
alias = ["gh"]
default = true

# Default if no repos are configured:
[repo]
default = "$XDG_DATA_HOME/git-repo-manager/${host/name}/${repo/url/hash}.git"

[checkout]
default = "~/projects/${host/name}/{$repo/name}"
# other = { path = "~/other-projects/", default = false }

[open]
# Open bash
# The current working directory is automatically set to ${repo-checkout}
default = ["bash"]

[open.notes]
command = ["bash"]
working-directory = "${repo/file-path}/notes"

[open.notes.merge]
# only apply config entry if entry is present
# only-if = "present"

# only apply config entry if entry is not present
# only-if = "not-present"

# apply config entry regardless whether the entry is present
only-if = ""

behavior = "merge"
# behavior = "replace"
